<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\AssemblyInfo.props" />

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>SoftWell.Fpml.Confirmation.Serialization.Xml</AssemblyName>
    <RootNamespace>SoftWell.Fpml.Confirmation.Serialization.Xml</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="PolySharp" Version="1.15.0">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="8.0.1"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Confirmation.Abstractions/Confirmation.Abstractions.csproj" />
    <ProjectReference Include="../Xml/Xml.csproj" />
  </ItemGroup>

</Project>
