<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\AssemblyInfo.props" />

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>SoftWell.Fpml.Serialization.Abstractions</AssemblyName>
    <RootNamespace>SoftWell.Fpml.Serialization</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="PolySharp" Version="1.15.0">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>

</Project>
