<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\AssemblyInfo.props" />

  <PropertyGroup>
    <TargetFrameworks>net7.0;net8.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>SoftWell.Fpml.Serialization.Abstractions</AssemblyName>
    <RootNamespace>SoftWell.Fpml.Serialization</RootNamespace>
  </PropertyGroup>

</Project>
